{% set name = "ez_setup" %}
{% set version = "0.9" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "303c5b17d552d1e3fb0505d80549f8579f557e13d8dc90e5ecef3c07d7f58642" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - wheel

  run:
    - python

test:
  commands:
    - pip check
  import:
    - ez_setup

about:
  home: https://github.com/ActiveState/ez_setup
  license: MIT
  license_family: MIT
  summary: 'ez_setup.py and distribute_setup.py'
  dev_url: https://github.com/ActiveState/ez_setup
  doc_url: https://github.com/ActiveState/ez_setup/blob/master/README.rst

extra:
  anaconda-services:
    reason: Dependency for apache-airflow
    recipe-maintainers:
      - ianaobi
  recipe-maintainers:
    - pmlandwehr
