travis:
  secure:
    BINSTAR_TOKEN: PjpQlM03Yieuw5KTlSdrrZzFRy+Uyefcky4+cs2new6pO/2PBp590gx9qFsRPZIzFwHaCd/Kp/zI2J2chT/Y3OM5OVpkoCuKIKxEt8czW2uu1J6NSkxQ4UTLu6Ddzj9I4PRqBp5aMcUetPqKx4+7xRr0uTszftI5H73T9N1zg2SKkknfiwyLoUr5DbUgqIGxzB18r3zghrReobYpnvAxJJT75uhRapED/Nc+0Bh4YXmrAjw/yVzuha1+hqaR7NvpuW9YlFs6KzlvXPIzyXxxDiATAaw4N9CZMnhB9zUw9r0V5wxNiBOKdvRaDmMBWp6cLcgUlJuEXCSLf+dfHTUeKKhLRCrP1ALo1UVSRIh67dQkLZpRO9RJovLAun9uInsqMAxxbLBlZ9pummC0BbgNmmedcuqGRDdV7ryjyPt6Vb8F9fuKCHbVdC/mVzdJaPPlFqa/H9JeNG6SlOpVSUGyTPJnQeNjgAIPxyygTMfFX9n73WfWLsBlyM52pi1PxEKh8HIQZ4ltbwRWZNDFLC3D/8MKMFKR2i9Q84uyT7k78NZ+kte3p//EDZEFEtT43mhmG8u0sghecEqaM8zzewHnIYgUlmhuco8J+5dCiXAtgy9b5Dix9iALwnvbavIqzHR4DMq/92EDh748vgYqIBUFHqwKbjiS26FYl0bXHPHQ/40=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
