travis:
  secure:
    BINSTAR_TOKEN: SUE7OtjZpi6e3dDtlMad5Xjxgao+Q7rk/QCbskUaj58JXwlbi9yYY4K7pHc39jI10OnPtswVo+jCoygk1CJcr+HeCpK6nsqpYllVBfcMYLPPhuz76yMD7QmNPLWmLczNxabYt1VnJLykwEa6g4h0/kfXNasXTmVqmb1lMW0cTIsvzNH3QcReOuou3eAMGZbBneQ3ouyQwyKuUg/KBfY+0rQvNWQHQA2zC7dC6ixDCO83Jg7LrfkfJaFWJdere4D2KYDHod/T8aF2urwnS5lCbhLzdVGJacdBtBOw4o9te3UQYJ7fh1LMgPYXBTbo/J1jz3ORAu50C5nIdbBEm0Rxu5vRD4jl20eip0TdE4yRIvZYQzTE6kWfJZcHgWdku049A8yUZTVplE5epvvg8XdpWGceZgwOLWlalCKskDs70kwfmPq4vn2Vr2FRsQD9rdurJjqlQEy1l6Nqibmuvlll1XBRj7FoI8LAeB5VU3XZQ8xjDQrHZEhqwt0KRv0Jo25QWF3gDA/muMEMkx8KBd2fzkvkmV92vB6a8Cw85ni51ydkvlF6JiXEXUjTQw2vtqtpqKeXjjPHT4tWlFsbs4sld2UzoQMuN6Udb3nZV9uE+nN2vstCXobU0LLB3e92/ZW4ZgYB7utEExTuXqsGC2RY1wJSzYW+7MEzM1eQmQAlOt0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
